aerospike/aerospike-client-python

scripts/aerospike-client-c.sh

``pip instlal aerospike`` when error on Scientific Linux 6.
without LSB:
```
info: Executing ./scripts/aerospike-client-c.sh
which: no lsb_release in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
error:  is not supported.
error: scripts/aerospike-client-c.sh 1
```
with LSB:
```
info: Executing ./scripts/aerospike-client-c.sh
error: scientific6 is not supported.
error: scripts/aerospike-client-c.sh 1
```

Add support to Scientific Linux 6.x

---

src/main/conversions.c
test/test_apply.py

When I run the test mentioned in #63, I get the following output:
$ python test_apply.py
First iteration
(('test', 'demo', None, bytearray(b'\xf5~\xc1\x835\xf7\x10\x0c\x04X\xf8\xa6D\xbc\xbcvm\x93G\x1e')), {'gen': 45, 'ttl': 4294967295}, {'param2': 'baz', 'param1': 20})
Second iteration
(('test', 'demo', None, bytearray(b'\xf5~\xc1\x835\xf7\x10\x0c\x04X\xf8\xa6D\xbc\xbcvm\x93G\x1e')), {'gen': 46, 'ttl': 4294967295}, {'param1': 30})
Aerospike log:
Jun 26 2015 22:52:13 GMT: WARNING (udf): ([C]::-1) Parameters: 20, baz
Jun 26 2015 22:52:13 GMT: WARNING (udf): ([C]::-1) Parameters: 30, nil

Convert Python's None to AS equivalent [Fixes #63]

---

src/main/scan/foreach.c

1. return false to stop the scan when callback raises exception
2. less judgmental error statement
3. fixed whitespace

bug fix: terminate a scan if callback raises exception

---

scripts/os_version

The content of my '/etc/issue' is 
```
Red Hat Enterprise Linux Server release 6.2 (Santiago)
Kernel \r on an \m
```
Need add space into `os_version` for right definition of RHEL.
Another example https://www.cyberciti.biz/faq/what-version-of-redhat-linux-am-i-running/

Fix os_version for right definition of RHEL

---

setup.py

A quick-n-dirty fix for installation on Mac OS X 10.15.2 using Python 3.8.1.

Fix installation in Python 3.8.1 on Mac OS X 10.15.2 (#250)

---

src/main/client/truncate.c

Fix syntax error in truncate.c causing the below exception:
src/main/client/truncate.c:133:5: error: expected '(' after 'if'
if PyLong_Check(py_nanos) {
^

Fix syntax error in truncate.c

---

doc/client.rst
doc/query.rst
doc/requirements.txt
doc/scan.rst

Add a requirements file to the docs directory instructing readthedocs.org to build the docs with a specific sphinx version. Also adjust some 5.0.0 Aerospike expressions related documentation.

Add requirements.txt for readthedocs.org

---

.build.yml
.gitmodules
src/main/client/bit_operate.c

All test cases pass on M1 using Kubelab to run the Aerospike server and the C client on commit [84cfce3](https://github.com/aerospike/aerospike-client-c/commit/84cfce3dda7216b05b39b0be437b570e30b2f06f).
We need to change the C client submodule to point to the master branch before merging.

Support M1/ARM

---

.flake8
.github/workflows/tests.yml
BUILD.md

- Splits up test workflow job into multiple jobs to get all info in parallel
- Use flake8 config file instead of command line arguments (and update instructions)
- Run build, install, and integration tests on all supported Python versions
- Show preview of ReadTheDocs docs for PRs

[CLIENT-1962] Split up github actions test workflow into multiple jobs

---

.github/workflows/tests.yml

Server 5.7 is reaching end of life soon so test server 6.0 instead

[CLIENT-2214] Ensure integration tests can run on lowest supported server version

---

.github/workflows/build-alpine.sh
.github/workflows/build-rhel9.sh
.github/workflows/tests.yml
doc/aerospike.rst
doc/exception.rst
src/include/exception_types.h
src/main/client/type.c
src/main/exception.c
test/new_tests/as_errors.py
test/new_tests/as_status_codes.py
test/new_tests/test_max_error_rate.py

enables to add [max_error_rate](https://github.com/aerospike/aerospike-client-c/blob/f7af9db267abe6d61bd6a2b6fc2424d3687e6d7d/src/include/aerospike/as_config.h#L584) and [error_rate_window](https://github.com/aerospike/aerospike-client-c/blob/f7af9db267abe6d61bd6a2b6fc2424d3687e6d7d/src/include/aerospike/as_config.h#L594) to config.

[CLIENT-2288] aerospike.client(): add client config options "max_error_rate" and "error_rate_window"

---

.github/workflows/build-rpm-based.sh
.github/workflows/build-wheels.yml
BUILD.md
README.rst

Build wheels test passes (including cat 1 and 2 tests on amazon linux 2023): https://github.com/aerospike/aerospike-client-python/actions/runs/5060092538
No new memory errors or leaks compared to stage branch:
Valgrind on this branch: https://github.com/aerospike/aerospike-client-python/actions/runs/5059901244
Valgrind on stage: https://github.com/aerospike/aerospike-client-python/actions/runs/5061600174

[CLIENT-2303] Add support for Amazon Linux 2023

---

aerospike_helpers/expressions/base.py
aerospike_helpers/expressions/resources.py
src/main/convert_expressions.c
test/new_tests/test_expressions_base.py

Build wheels test passing except for some noise: https://github.com/aerospike/aerospike-client-python/actions/runs/5092347763
**Valgrind**
There seems to be 4 less memory leaks in this branch compared to the stage branch. No new memory errors in this branch were found.
stage branch: https://github.com/aerospike/aerospike-client-python/actions/runs/5092349440/jobs/9153578570
this branch: https://github.com/aerospike/aerospike-client-python/actions/runs/5092345365/jobs/9153569568

[CLIENT-2228] Add support for expression values

---

doc/client.rst
test/new_tests/test_admin_query_user.py
test/new_tests/test_admin_query_user_info.py
test/new_tests/test_admin_query_users.py
test/new_tests/test_admin_query_users_info.py

Updated docs: https://aerospike-python-client--457.org.readthedocs.build/en/457/client.html#aerospike.Client.admin_query_user_info
Build wheels and valgrind workflow runs aren't necessary since the source code and test coverage have not been changed.

[CLIENT-2363] Document client.admin_query_user[s]_info() and deprecate client.admin_query_user[s]

---

doc/client.rst
test/new_tests/test_batch_get_ops.py

Docs: https://aerospike-python-client--464.org.readthedocs.build/en/464/client.html#aerospike.Client.batch_get_ops
Tests for function are skipped now: https://github.com/aerospike/aerospike-client-python/actions/runs/5511781847/jobs/10047812433?pr=464#step:10:462

[CLIENT-2409] Deprecate client.batch_get_ops()

---

doc/client.rst

Docs: https://aerospike-python-client--466.org.readthedocs.build/en/466/client.html#methods

[DOCS-861] aerospike.Client: add reference to client constructor in aerospike module

---

test/new_tests/test_expressions_base.py

Mark will add a test for MemorySize() in test cat 3

[CLIENT-2221] Skip MemorySize() test due to QE tests #1 and #2 failing

---

.readthedocs.yml

Proof it works again: https://aerospike-python-client--482.org.readthedocs.build/en/482/index.html

[CLIENT-2507] Add .readthedocs.yml config to build Python client documentation website

---

doc/data_mapping.rst
doc/spelling_wordlist.txt
src/main/serializer.c

Cherry-picked from #486
Build wheels passes: https://github.com/aerospike/aerospike-client-python/actions/runs/5881769138
Verification that it works:
1. I stored a tuple that was serialized with cPickle using Python client 12.0.0, then stored in the server as an AS_BYTES_PYTHON type.
2. I installed Python client built on this branch (11.2.0) and it returns the AS_BYTES_PYTHON as a bytearray without deserializing it. If you manually deserialize it without using the client, you still get the original object that was serialized with cPickle.
```bash
jnguyen@as-PF3WN8Y6:~/aerospike/aerospike-client-python$ python3 -m pip install aerospike==12.0.0
...
jnguyen@as-PF3WN8Y6:~/aerospike/aerospike-client-python$ python3
Python 3.9.16 (main, Feb  8 2023, 16:50:17) 
[GCC 11.3.0] on linux
Type "help", …
```

[CLIENT-2258] Backport 11.*: Convert AS_BYTES_PYTHON server type to Python bytearray

---

doc/aerospike.rst

https://aerospike-python-client--499.org.readthedocs.build/en/499/aerospike.html#aerospike.LIST_RETURN_EXISTS

[CLIENT-2460] Docs: Add missing constant aerospike.LIST_RETURN_EXISTS

---

aerospike_helpers/batch/records.py

https://aerospike-python-client--498.org.readthedocs.build/en/498/aerospike_helpers.batch.html#aerospike_helpers.batch.records.Apply
https://aerospike-python-client--498.org.readthedocs.build/en/498/aerospike_helpers.batch.html#aerospike_helpers.batch.records.Remove

[CLIENT-1977] Docs: Remove nonexistent "ops" field for BatchRemove and BatchApply records

---

.github/workflows/build-wheels.yml
BUILD.md
README.rst

Build wheels workflow still works: https://github.com/aerospike/aerospike-client-python/actions/runs/6776927253

[CLIENT-2654] Remove Debian 10 support

---

.github/workflows/build-wheels.yml

Build wheels runs:
1. https://github.com/aerospike/aerospike-client-python/actions/runs/7453600256
2. https://github.com/aerospike/aerospike-client-python/actions/runs/7453599302
3. https://github.com/aerospike/aerospike-client-python/actions/runs/7453580753
Only 1/24 tests failed, which is a better result than what we currently are getting. About half of the time, colima fails to let us connect to a Docker container.

[CLIENT-2742] CI/CD: Use larger runners for macOS x86 tests

---

.github/workflows/build-wheels.yml
.github/workflows/dev-workflow-p1.yml
.github/workflows/dev-workflow-p2.yml
.github/workflows/tests.yml
.github/workflows/update-version.yml

Improvements:
- Update cibuildwheel version to v2.16.5
- Add option to run dev-workflow-p2 workflow manually
- Rename PR pre-merge tests workflow to "PR tests"
- Skip PR tests on bump commits
- Run PR tests on mock branches (i.e dev-test)
Fixes:
- Build Windows x86 Python 3.12 wheel
- Fix checking out the wrong commit for windows builds and tests
- Fix Windows wheels not being uploaded to JFrog
- Fix dev-workflow-p1 workflow not running when review is requested on a PR
Testing
Bump commits skip CI/CD workflow: https://github.com/aerospike/aerospike-client-python/commits/dev-test/
Windows wheels including Python 3.12 successfully uploaded to JFrog: https://github.com/aerospike/aerospike-client-python/actions/runs/7995790908/job/21837350699

[CLIENT-1837] CI/CD: Fix minor issues and make improvements to pipeline

---

src/main/conversions.c
src/main/key_ordered_dict/type.c
test/new_tests/test_get_put_keyordereddict.py

Valgrind (no memory errors or leaks from PR): https://github.com/aerospike/aerospike-client-python/actions/runs/7996974797
Build wheels: https://github.com/aerospike/aerospike-client-python/actions/runs/7997568091

[CLIENT-2077] Add support for reading key ordered maps

---

doc/aerospike.rst
doc/data_mapping.rst
test/new_tests/test_expressions_map.py
test/new_tests/test_geospatial.py

Docs:
https://aerospike-python-client--584.org.readthedocs.build/en/584/aerospike.html#aerospike.POLICY_KEY_SEND
https://aerospike-python-client--584.org.readthedocs.build/en/584/data_mapping.html#data-mappings
Extra changes:
- Modified test_expressions_map.py so it passes on both servers < 7.1 and server 7.1.
- test_geospatial.py: only run certain tests on server < 7.1

[CLIENT-2444] Docs: Add note about POLICY_KEY_SEND and list possible map key types

---

.github/workflows/upload-jfrog-build-to-pypi.yml

Successful download and publishing of JFrog artifacts to Test PyPI: https://github.com/aerospike/aerospike-client-python/actions/runs/8606094945/job/23583782412
Publishing a nonexistent JFrog build fails: https://github.com/aerospike/aerospike-client-python/actions/runs/8606227878/job/23584197210

[CLIENT-1837] CI/CD: Add option to upload JFrog builds to PyPI

---

doc/client.rst
doc/examples/batch_operate.py

https://aerospike-python-client--594.org.readthedocs.build/en/594/client.html#aerospike.Client.batch_operate

[CLIENT-2851] Doc: Add note about bug with passing only read operations in client.batch_operate()

---

.github/workflows/tests.yml

Reran coverage upload job twice and it passes again

[CLIENT-2203] CI/CD: Fix codecov.io upload errors by using a token

---

.github/workflows/stage-tests.yml
README.rst

Extra changes:
- Fix bug where macOS stage tests always use server RC
Tests pass on macOS 13: https://github.com/aerospike/aerospike-client-python/actions/runs/8884125090/job/24393025635

[CLIENT-2904] Add support for macOS 13

---

.github/workflows/stage-tests.yml
README.rst

Stage tests without macos 11: https://github.com/aerospike/aerospike-client-python/actions/runs/8898394464

[CLIENT-2736] Remove macOS 11 support

---

src/main/conversions.c
src/main/serializer.c

Memory usage after running the full test suites is now back to normal as before the metrics changes. No memory errors from running valgrind on this branch
dev: https://github.com/aerospike/aerospike-client-python/actions/runs/8884233073
this branch: https://github.com/aerospike/aerospike-client-python/actions/runs/8897726512
Before metrics changes: https://github.com/aerospike/aerospike-client-python/actions/runs/8886114249

[CLIENT-2701] Fix memory leak that occurs when creating an aerospike_helpers class instance with a parameter

---

aerospike_helpers/operations/map_operations.py
test/new_tests/test_map_operation_helpers.py
test/new_tests/test_operate_map.py

Added missing test coverage for map operations to check if deleting all map items yields an empty map
Documentation changes:
https://aerospike-python-client--615.org.readthedocs.build/en/615/aerospike_helpers.operations.html#module-aerospike_helpers.operations.map_operations
Tests already exist for:
- map_clear(): https://github.com/aerospike/aerospike-client-python/blob/CLIENT-2856-doc-map-policy/test/new_tests/test_nested_cdt_ctx.py#L2923
- map_remove_by_key_list(): https://github.com/aerospike/aerospike-client-python/blob/CLIENT-2856-doc-map-policy/test/new_tests/test_nested_cdt_ctx.py#L3174
- map_remove_by_index_range(): https://github.com/aerospike/aerospike-client-python/blob/CLIENT-2858-clarify-empty-maps/test/new_tests/test_nested_cdt_ctx.py#L4019
- …

[CLIENT-2858] Docs: Clarify that deleting all keys in a map does not delete the map itself

---

aerospike_helpers/operations/map_operations.py
doc/client.rst

Extra changes
- Add missing default value for persist_index option in map policy
Doc changes
Default value for persist_index: https://aerospike-python-client--614.org.readthedocs.build/en/614/client.html#map-policies
map_set_policy() description changed: https://aerospike-python-client--614.org.readthedocs.build/en/614/aerospike_helpers.operations.html#aerospike_helpers.operations.map_operations.map_set_policy
Map API description changed:
https://aerospike-python-client--614.org.readthedocs.build/en/614/aerospike_helpers.operations.html#aerospike_helpers.operations.map_operations.map_increment
https://aerospike-python-client--614.org.readthedocs.build/en/614/aerospike_helpers.operations.html#aerospike_helpers.operations.map_operations.map_decrement

[CLIENT-2856] Docs: Clarify how map policy works for all map operations that use it

---

aerospike_helpers/operations/list_operations.py
doc/aerospike.rst
test/new_tests/test_operate_helpers.py

addresses issues 5 and 6 by customer
Extra changes. These is behavior not documented in the Python client but is documented in the C client:
- https://aerospike-python-client--602.org.readthedocs.build/en/602/aerospike_helpers.operations.html#aerospike_helpers.operations.list_operations.list_insert_items
- https://aerospike-python-client--602.org.readthedocs.build/en/602/aerospike_helpers.operations.html#aerospike_helpers.operations.list_operations.list_remove
- https://aerospike-python-client--602.org.readthedocs.build/en/602/aerospike_helpers.operations.html#aerospike_helpers.operations.list_operations.list_remove_range
- https://aerospike-python-client--602.org.readthedocs.build/en/602/aerospike_helpers.operations.html#aerospike_helpers.operations.list_operations.list_set
Negative …

[CLIENT-2856] Docs: Clarify how list order works and add link to explain negative indices

---

.github/actions/update-version/action.yml
BUILD.md
doc/aerospike.rst
scripts/manylinux2014build.sh
src/main/aerospike.c
test/new_tests/test_connect.py

Doc changes
https://aerospike-python-client--623.org.readthedocs.build/en/623/aerospike.html#miscellaneous
Regression test
Workflow to bump and update version still works: https://github.com/aerospike/aerospike-client-python/actions/runs/9287695613
TODO

[CLIENT-1938] Remove aerospike.__version__ to single source the client's version

---

.github/workflows/valgrind.yml

TODO: need to optimize valgrind workflow by only building manylinux wheels and ignoring all the other platforms. Currently working on this in another PR for refactoring the GHA code
These changes seem to work as tested in CLIENT-681-Refactor branch

[CLIENT-2970] CI/CD: Use manylinux wheel instead of a local build for valgrind workflow

---

.github/workflows/upload-jfrog-build-to-pypi.yml

This fix allowed me to upload 15.0.1rc2 from JFrog to PyPI: https://github.com/aerospike/aerospike-client-python/actions/runs/9323099458
The test.pypi.org link worked before, but not the pypi.org link

[CLIENT-1837] CI/CD: Fix using the wrong repository URL when uploading JFrog builds to pypi.org

---

.github/actions/run-ee-server/action.yml
.github/workflows/build-wheels.yml
.github/workflows/tests.yml
.github/workflows/valgrind.yml
.gitmodules

C client changes: https://github.com/aerospike/aerospike-client-c/compare/d1f5afbf09349dbeb5a9dda877d906ea5820a236...54e25075646e815f023b5923603d35fa9d9b8f00
All wheels pass testing except for some noise and syntax errors in the workflow code. I think it's sufficient enough to pass: https://github.com/aerospike/aerospike-client-python/actions/runs/9716046629/job/26818853889
Valgrind shows no memory errors coming from this PR: https://github.com/aerospike/aerospike-client-python/actions/runs/9716555070

[CLIENT-3000] Fix scans not working for a mixed cluster of 5.7 and 6.4 nodes (v13 backport)

---

.github/actions/run-ee-server/action.yml
.github/workflows/build-wheels.yml
.github/workflows/stage-tests.yml
.github/workflows/test-server-rc.yml

Build wheels:
https://github.com/aerospike/aerospike-client-python/actions/runs/9881629015
Stage tests run 3 times to make sure ARM jobs pass consistently:
1-2. https://github.com/aerospike/aerospike-client-python/actions/runs/9882439609
3. https://github.com/aerospike/aerospike-client-python/actions/runs/9883470808
dev-workflow-p1: https://github.com/aerospike/aerospike-client-python/actions/runs/9894525911/job/27332464333

[CLIENT-2996] CI/CD: Use Github ARM runners for ARM jobs

---

.github/workflows/build-wheels.yml

First run (installs Python for first time): https://github.com/aerospike/aerospike-client-python/actions/runs/10152681659/job/28074723508
Rerun (uses cached setup-python installs): https://github.com/aerospike/aerospike-client-python/actions/runs/10152790089

[DEVOPS-255] CI/CD: Use setup-python action to install Python on Windows self-hosted runners

---

.github/workflows/build-wheels.yml

- EE tests pass on Mac M1
- setup buildx action works on Mac M1 self hosted
Mac M1 tests pass twice: https://github.com/aerospike/aerospike-client-python/actions/runs/10219987761
TODO: next week I need to ensure that the Mac M1 runners are reset to a clean slate after each job

[CLIENT-3063] CI/CD: Run enterprise edition tests on wheels built for Mac arm64 (M1)

---

.github/actions/run-ee-server/action.yml
.github/workflows/build-wheels.yml
.gitmodules

C client changes: https://github.com/aerospike/aerospike-client-c/compare/29860294a714d254c71d4325d8242b66f7a773eb...54e25075646e815f023b5923603d35fa9d9b8f00
All wheels pass testing except for noise and some bugs in the workflow code: https://github.com/aerospike/aerospike-client-python/actions/runs/9666696374/
Valgrind shows no new memory errors from this PR: https://github.com/aerospike/aerospike-client-python/actions/runs/9717949772

[CLIENT-3000] Fix scans not working for a mixed cluster of 5.7 and 6.4 nodes (v14 backport)

---

aerospike_helpers/expressions/resources.py
test/new_tests/test_expressions_map.py

Doc changes:
https://aerospike-python-client--658.org.readthedocs.build/en/658/aerospike_helpers.expressions.html#module-aerospike_helpers.expressions.resources

[CLIENT-3057] Add missing aerospike_helpers.expressions.resources.ResultType constant NIL

---

src/main/exception.c

None's reference count needs to be managed properly for Python 3.11 and lower
https://docs.python.org/3.11/c-api/none.html#c.Py_None
https://docs.python.org/3.12/c-api/none.html#c.Py_None
Massif memory usage seems ok: https://github.com/aerospike/aerospike-client-python/actions/runs/10887384965/job/30209613022
No memory errors from valgrind: https://github.com/aerospike/aerospike-client-python/actions/runs/10887382672
Build wheels macOS x86 tests fail fast even though I disabled that. Have to investigate later, but besides that, it should be fine

[CLIENT-3106] Fix reference count error caused by not properly incrementing reference count for Py_None object

---

.github/workflows/build-wheels.yml
.github/workflows/manylinux2014-openssl.Dockerfile

- Negative testing passes. repair step fails if wrong openssl version is used
- Repair step passes if correct openssl version is used
TODO
- Delete branch for negative testing

[CLIENT-2217] CI/CD: Verify we are linking the wheel with the correct OpenSSL version

---

doc/client.rst
doc/query.rst
doc/scan.rst

Docs: https://aerospike-python-client--708.org.readthedocs.build/en/708/client.html#read-policies

[CLIENT-3228] Docs: Clarify that the "compress" policy requires enterprise edition

---

doc/client.rst
doc/on_locking_only.rst
doc/txn.rst
src/main/policy.c

Valgrind shows no memory errors. Massif memory usage looks ok
Build artifacts passes
Doc changes
https://aerospike-python-client--713.org.readthedocs.build/en/713/client.html#write-policies
Extra changes:
- Add note that the "txn" field only works for transaction level policies
Misc notes:
- Missing gray background behind "txn" and "on_locking_only" policy names, but I don't think this is a big deal
- Discussed with Brian Nichols and I decided to only allow on_locking_only for transaction level policies. I only think users would only set MRTs using transaction level policies.

[CLIENT-3264] Add on_locking_only option for write, apply, operate, batch_write, and batch_apply policies

---

.github/workflows/tests.yml
doc/aerospike.rst
src/main/policy_config.c
test/new_tests/test_new_constructor.py

https://aerospike-python-client--715.org.readthedocs.build/en/715/aerospike.html#client-configuration
Valgrind shows no memory errors, massif memory usage looks ok, build artifacts passes
Test on lowest supported server failing due to C client bug, will be fixed in a future C client revision
Extra changes:
CI/CD: Update upload-artifact and download-artifact from v3 to v4 to fix workflows not running

[CLIENT-3121] Add "txn_verify" and "txn_roll" config policies

---

.gitmodules

Fix was verified by running this test with valgrind: https://github.com/citrusleaf/devtools/tree/master/aerolab/core/batch-client-crash
Valgrind shows no memory errors.
Massif memory usage looks normal
Build artifacts passes

[CLIENT-3307] Fix stack overflow when sending a batch command with many keys

---

src/main/client/batch_write.c
test/new_tests/test_batch_write.py

Still potential memory leaks in batch_write(), but need to ship this fix ASAP for a customer.
Will rebase and merge on approval
Manual Testing
Build artifacts passes except noise
valgrind shows no memory errors, massif mem usage looks ok
Leak is gone now when running support team's script
Extra changes:
- Rename label so it is easier to understand when the label is used

[CLIENT-3382] Fix 2 memory leaks in client.batch_write()

---

aerospike_helpers/expressions/bitwise.py

https://aerospike-python-client--771.org.readthedocs.build/en/771/aerospike_helpers.expressions.html#aerospike_helpers.expressions.bitwise.BitResize
https://aerospike-python-client--771.org.readthedocs.build/en/771/aerospike_helpers.expressions.html#aerospike_helpers.expressions.bitwise.BitAdd
https://aerospike-python-client--771.org.readthedocs.build/en/771/aerospike_helpers.expressions.html#aerospike_helpers.expressions.bitwise.BitSubtract

[CLIENT-2169] Docs: add missing references to aerospike enums for certain bitwise operations

---

src/main/client/batch_read.c

Valgrind shows no memory errors and that this leak from batch_read() is now gone
Build artifacts passes when running against test_batch_read.py

[CLIENT-3478] client.batch_read(): fix memory leak if bins parameter is invalid

---

src/main/predicates.c
src/main/query/where.c
test/new_tests/test_query.py

All tests passing except for one because of a broken link in docs (unrelated)
Extra changes:
Add test coverage for cleaning up `ctx` if query.where() fails and for passing an invalid predicate type
Prep work for sindex expression changes
Notes:
- There's a TODO about how static pool is used in where.c, but Dominic is currently working on a PR to replace it with dynamic pool, so I think we can leave that as-is for now. This PR shouldn't change the behavior of the static pool
No breaking changes in predicates.c, since predicates are also used in client.query_apply()
---
Build artifacts passes
Valgrind shows no memory errors or leaks from these changes
Massif usage looks ok
Verified with Brian Nichols that the refactoring looks ok

[CLIENT-3497] Refactor query.where() without sindex expression changes
